Build script improvements

diff --git a/build b/build
--- a/build
+++ b/build
@@ -40,19 +40,22 @@ MODS_DIR="$BUILD_DIR"/mods/modified
 # ADDONS
 ADDONS_DIR="$BUILD_DIR"/addons
 
+init() {
+	if [ ! -e "$DIST" ];then
+                mkdir -p "$DIST"
+                mkdir -p "$DIST"/addons
+        fi
 
-echo "$BUILD_DIR"
+	if [ ! -e "$OPEN_GAPPS_INSTALL" ];then
+                mkdir -p "$OPENGAPPS_INSTALL"
+        fi
+}
 
 buildROM() {
 
 	if [ ! -e "$KERNEL_DIST"/boot.img ];then
 		echo "Kernel not built, you cannot continue with the build"
 		exit 255
-	fi
-
-	if [ ! -e "$DIST" ];then
-		mkdir -p "$DIST"
-		mkdir -p "$DIST"/addons
 	fi
 
 	rm -rf "$DIST"/"$ROMNAME"-*.zip
@@ -124,6 +127,7 @@ buildApps() {
 		done
 		cd ..
 	fi
+	cd "$BUILD_DIR"
 }
 
 buildAddons() {
@@ -138,7 +142,7 @@ buildAddons() {
 			echo "No Addons to zip"
 		fi
 	done
-	cd ..
+	cd "$BUILD_DIR"
 }
 
 buildKernel() {
@@ -151,6 +155,8 @@ buildKernel() {
 		echo "Kernel failed to build"
 		exit 0
 	fi
+
+	cd "$BUILD_DIR"
 }
 
 buildGapps() {
@@ -165,15 +171,16 @@ buildGapps() {
 		cd opengapps
 	 	./download_sources.sh
 		make "$OPENGAPPS_ARCH"-"$OPENGAPPS_API"-"$OPENGAPPS_VARIANT"
-		cd ..
+		cd "$BUILD_DIR"
 	fi
 
-	if [ ! -e "$OPEN_GAPPS_INSTALL" ];then
-		mkdir -p "$OPENGAPPS_INSTALL"
+	if [ -e "$OPENGAPPS_OUT"/"$OPENGAPPS_ZIP" ];then
+		echo "Copying Gapps to Install folder"
+		cp "$OPENGAPPS_OUT"/"$OPENGAPPS_ZIP" "$OPENGAPPS_INSTALL"/opengapps.zip
+	else
+		echo "Error, GAPPS not present. Exiting"
+		exit 255
 	fi
-
-	echo "Copying Gapps to Install folder"
-	cp "$OPENGAPPS_OUT"/"$OPENGAPPS_ZIP" "$OPENGAPPS_INSTALL"/opengapps.zip
 }
 
 checkForUpdates() {
@@ -198,6 +205,7 @@ start() {
 	done
 }
 
+init
 start
 
 exit 0
